version: '3'

services:
  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: newdb
    ports:
      - 3306:3306
  api:
    container_name: api
    build: ./car-rental
    ports:
      - 8000:8080
    depends_on:
      - db

